image: "node:8-alpine"

before_script:
   - apk add 'git=~2'
   - node --version
   - npm --version
   - git --version
   - npm ci

audit:
  script: npm audit

lint:
  script: npm run lint

build8:
  script: npm run build

build10:
  image: "node:10-alpine"
  script: npm run build

build12:
  image: "node:12-alpine"
  script: npm run build

test:
  script: npm run test