image: "node:8-alpine"

before_script:
   - apk add 'git=~2'
   - npm ci

stages:
  - static-checks
  - build
  - tests

audit:
  stage: static-checks
  script: npm audit

lint:
  stage: static-checks
  script: npm run lint

build:
  stage: build
  script: npm run build

test:
  stage: tests
  script:
    - node --version
    - npm --version
    - git --version
    - npm run test