default:
  image: "node:8-alpine"
  before_script:
    - apk add 'git=~2'
    - node --version
    - npm --version
    - git --version
    - npm ci

Audit:
  script: npm audit

Lint:
  script: npm run lint

Build:
  script: npm run build

"Test - node 8":
  script: npm run test

"Test - node 10":
  image: "node:10-alpine"
  script: npm run test

"Test - node 12":
  image: "node:12-alpine"
  script: npm run test
