#!/bin/sh

# This hook file enables Git LFS at the same time as Husky
# See: https://gitmemory.com/issue/typicode/husky/108/493582447
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
git lfs post-checkout "$@"